
version: "3.9"
services:
  #Container do MySQL
  mysqlsrv:
    container_name: mysql_desafio
    image: mysql:5.7
    volumes:
      - /home/user/docker/volumes/mysql:/var/lib/mysql-files
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_desafio
    ports:
      - "3306:3306"